- name: Install google repo
  copy:
    content: "{{ common_gcloud_yum_repo }}"
    dest: /etc/yum.repos.d/google-cloud-sdk.repo

- name: Install epel repo
  yum:
    name: epel-release
    state: latest
    update_cache: yes

- name: Install Administration tools
  yum:
    name:
      - htop
      - tmux
      - google-cloud-sdk
      - unzip
      - wget
      - vim
      - tar
      - xz
      - mlocate
      - git
      - bash-completion
      - bash-completion-extras
      - libselinux-python
      - ntp
      - python-pip
    state: latest

- name: Install global python packages
  pip:
    name:
      - virtualenv
      - requests
      - pyyaml

- name: Update files db
  shell: updatedb

- name: Set time zone
  shell: timedatectl set-timezone UTC

- name: Sync time
  shell: timedatectl set-ntp true

