version: '3'
services:

  prometheus:
    build:
      context: ./prometheus
    image: "my-prometheus:latest"
    ports:
      - "9090:9090"

  node:
    build:
      context: ./node
    image: "node:latest"
    ports:
      - "9100:9100"

  alertmanager:
    build:
      context: ./alertmanager
    image: "alertmanager:latest"
    ports:
     - "9093:9093"

