global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
rule_files:
  - alert.rules.yml
alerting:
  alertmanagers:
    - static_configs:
      - targets: ["alertmanager:9093"]

scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
    - targets:
      - localhost:9090
  - job_name: node
    scrape_interval: 5s
    scrape_timeout: 4s
    metrics_path: /metrics
    static_configs:
      - targets: ['node:9100']
  - job_name: alertmanager
    scrape_interval: 15s
    scrape_timeout: 4s
    metrics_path: /metrics
    static_configs:
      - targets: ['alertmanager:9093']

