FROM centos:7
RUN yum install -y epel-release && yum install -y stress

ADD node_exporter /usr/local/bin/
ADD services_wrapper.sh /usr/local/bin/
RUN ["chmod", "+x", "/usr/local/bin/services_wrapper.sh"]

#CMD ["--cpu", "0", "--io", "10","--vm", "1", "--vm-bytes", "256M"]
CMD ["--io", "10","--vm", "1", "--vm-bytes", "256M"]
ENTRYPOINT ["/usr/local/bin/services_wrapper.sh"]

# docker build -t monitored/app:latest .
# docker run -it monitored/app