- name: Remove older versions of docker if installed
  yum:
    name: "{{ item }}"
    state: 'absent'
  with_items:
    - docker
    - docker-client
    - docker-client-latest
    - docker-latest-logrotate
    - docker-logrotate
    - docker-selinux
    - docker-engine-selinux
    - docker-engine

- name: Install Docker CE prerequisites
  yum:
    name: "{{ item }}"
    state: installed
  with_items:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Install docker repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: Install docker
  yum:
    name: "docker-ce-{{ docker_ce_version | default('17.12.1.ce-1.el7.centos.x86_64') }}"
    state: installed

- name: Start docker service
  systemd:
    name: docker
    state: started
    enabled: yes

- name: Add provisioning user to docker group - to fix permissions issue
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes

- name: Configure the Docker daemon
  template:
    src: docker_ce_daemon.json
    dest: /etc/docker/daemon.json
  notify:
    - restart docker


